[build]
  # Build command for Vite
  command = "npm run build"
  
  # Directory to publish
  publish = "dist"

[functions]
  # Directory for Netlify Functions
  directory = "netlify/functions"

# Redirect rules for SPA (Single Page Application)
# This ensures all routes are handled by index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers for Netlify Functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"

# Processing configuration
[build.processing]
  skip_processing = false