[build]
  # Build command for Vite
  command = "npm run build"
  
  # Directory to publish
  publish = "dist"

[functions]
  # Directory for Netlify Functions
  directory = "netlify/functions"

# Environment variables for Netlify Functions
# These should be set in Netlify Dashboard > Site Settings > Environment Variables
[build.environment]
  # Square Payment Configuration
  SQUARE_ENVIRONMENT = "sandbox"
  
# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers for Netlify Functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"
