[build]
  # Build command for Vite
  command = "npm run build"
  
  # Directory to publish
  publish = "dist"

[functions]
  # Directory for Netlify Functions
  directory = "netlify/functions"

# Redirect rules for SPA (Single Page Application)
# This ensures all routes are handled by index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers for Netlify Functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type"
    Access-Control-Allow-Methods = "POST, OPTIONS"

# Processing configuration
[build.processing]
  skip_processing = false

[build.environment]
# Tell Netlify secrets scanner to ignore these known non-secret VITE_* keys
# (These values are public identifiers used by the client and do not contain secrets.)
SECRETS_SCAN_OMIT_KEYS = "VITE_SQUARE_APPLICATION_ID,VITE_SQUARE_LOCATION_ID,VITE_SQUARE_ENVIRONMENT,SQUARE_ENVIRONMENT,SECRETS_SCAN_OMIT_KEYS"

# Optional: omit common build/output paths from secrets scanning if they contain only public identifiers
SECRETS_SCAN_OMIT_PATHS = "dist/**,node_modules/**"

# Note: Environment variables should be set in Netlify Dashboard
# Do NOT hardcode sensitive values here - they would be public in the repository